# Generated by Django 5.0.7 on 2025-01-10 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='username',
        ),
        migrations.AddField(
            model_name='account',
            name='first_name',
            field=models.TextField(default='', max_length=30, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='account',
            name='is_parent',
            field=models.BooleanField(default=True),
        ),
    ]
