# Generated by Django 5.0.7 on 2025-01-23 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_squashed_0002_account_date_of_birth'),
        ('studentVaccinations', '0004_remove_vaccinationrecord_date_administered'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='missing_vaccination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='studentVaccinations.vaccination'),
        ),
    ]
