# Generated by Django 5.0.7 on 2025-01-23 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_account_missing_vaccination'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='last_name',
            field=models.CharField(default='', max_length=30, verbose_name='last name'),
        ),
    ]
