# Generated by Django 5.0.7 on 2025-02-02 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_account_last_name'),
        ('studentVaccinations', '0006_alter_missingvaccination_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='missing_vaccination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='studentVaccinations.vaccination'),
        ),
    ]
