# Generated by Django 5.0.7 on 2025-01-16 00:21

import django_advance_thumbnail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentImages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='thumbnail',
            field=django_advance_thumbnail.fields.AdvanceThumbnailField(null=True, upload_to='thumbnails/'),
        ),
    ]
