# Generated by Django 5.0.7 on 2025-01-18 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentVaccinations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccination',
            name='requiredAgeInMonths',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vaccination',
            name='requiredAgeInDays',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
