# Generated by Django 5.0.7 on 2025-01-18 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentVaccinations', '0002_vaccination_requiredageinmonths_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccination',
            name='requiredAgeInDays',
        ),
    ]
