# Generated by Django 5.0.7 on 2025-01-21 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentVaccinations', '0003_remove_vaccination_requiredageindays'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccinationrecord',
            name='date_administered',
        ),
    ]
