# Generated by Django 5.0.7 on 2025-01-24 08:08

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime(2025, 1, 24, 8, 8, 53, 721903, tzinfo=datetime.timezone.utc))),
                ('breakfast', models.IntegerField(choices=[(0, 'Did Not Eat'), (1, 'Ate A Little'), (2, 'Ate Most'), (3, 'Ate All')])),
                ('lunch', models.IntegerField(choices=[(0, 'Did Not Eat'), (1, 'Ate A Little'), (2, 'Ate Most'), (3, 'Ate All')])),
                ('had_am_nap', models.BooleanField()),
                ('had_pm_nap', models.BooleanField()),
                ('am_nap_start_time', models.TimeField()),
                ('am_nap_end_time', models.TimeField()),
                ('first_milk_oz', models.IntegerField()),
                ('second_milk_oz', models.IntegerField()),
                ('third_milk_oz', models.IntegerField()),
                ('fourth_milk_oz', models.IntegerField()),
                ('first_milk_time', models.TimeField()),
                ('second_milk_time', models.TimeField()),
                ('third_milk_time', models.TimeField()),
                ('fourth_milk_time', models.TimeField()),
                ('bm_10AM', models.BooleanField()),
                ('bm_11AM', models.BooleanField()),
                ('bm_12PM', models.BooleanField()),
                ('bm_1PM', models.BooleanField()),
                ('bm_2PM', models.BooleanField()),
                ('bm_3PM', models.BooleanField()),
                ('bm_4PM', models.BooleanField()),
                ('bm_5PM', models.BooleanField()),
                ('bm_9AM', models.BooleanField()),
                ('bm_accident_10AM', models.BooleanField()),
                ('bm_accident_11AM', models.BooleanField()),
                ('bm_accident_12PM', models.BooleanField()),
                ('bm_accident_1PM', models.BooleanField()),
                ('bm_accident_2PM', models.BooleanField()),
                ('bm_accident_3PM', models.BooleanField()),
                ('bm_accident_4PM', models.BooleanField()),
                ('bm_accident_5PM', models.BooleanField()),
                ('comments', models.TextField(max_length=255)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
