# Generated by Django 5.0.7 on 2025-01-24 08:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyReport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 1, 24, 8, 31, 21, 124583, tzinfo=datetime.timezone.utc)),
        ),
    ]
