# Generated by Django 5.0.7 on 2025-02-02 03:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyReport', '0003_alter_dailyreport_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='bm_accident_9AM',
            field=models.BooleanField(null=True, verbose_name='Accident at 9 AM'),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='pm_nap_end_time',
            field=models.TimeField(null=True, verbose_name='Afternoon Nap End Time'),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='pm_nap_start_time',
            field=models.TimeField(null=True, verbose_name='Afternoon Nap Start Time'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Account'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='am_nap_end_time',
            field=models.TimeField(null=True, verbose_name='Morning Nap End Time'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='am_nap_start_time',
            field=models.TimeField(null=True, verbose_name='Morning Nap Start Time'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='bm_10AM',
            field=models.BooleanField(null=True, verbose_name='Bowel Movement at 10 AM'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='bm_11AM',
            field=models.BooleanField(null=True, verbose_name='Bowel Movement at 11 AM'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='bm_12PM',
            field=models.BooleanField(null=True, verbose_name='Bowel Movement at 12 PM'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='bm_1PM',
            field=models.BooleanField(null=True, verbose_name='Bowel Movement at 1 PM'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='bm_2PM',
            field=models.BooleanField(null=True, verbose_name='Bowel Movement at 2 PM'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='bm_3PM',
            field=models.BooleanField(null=True, verbose_name='Bowel Movement at 3 PM'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='bm_4PM',
            field=models.BooleanField(null=True, verbose_name='Bowel Movement at 4 PM'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='bm_5PM',
            field=models.BooleanField(null=True, verbose_name='Bowel Movement at 5 PM'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='bm_9AM',
            field=models.BooleanField(null=True, verbose_name='Bowel Movement at 9 AM'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='bm_accident_10AM',
            field=models.BooleanField(null=True, verbose_name='Accident at 10 AM'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='bm_accident_11AM',
            field=models.BooleanField(null=True, verbose_name='Accident at 11 AM'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='bm_accident_12PM',
            field=models.BooleanField(null=True, verbose_name='Accident at 12 PM'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='bm_accident_1PM',
            field=models.BooleanField(null=True, verbose_name='Accident at 1 PM'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='bm_accident_2PM',
            field=models.BooleanField(null=True, verbose_name='Accident at 2 PM'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='bm_accident_3PM',
            field=models.BooleanField(null=True, verbose_name='Accident at 3 PM'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='bm_accident_4PM',
            field=models.BooleanField(null=True, verbose_name='Accident at 4 PM'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='bm_accident_5PM',
            field=models.BooleanField(null=True, verbose_name='Accident at 5 PM'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='breakfast',
            field=models.IntegerField(choices=[(0, 'Did Not Eat'), (1, 'Ate A Little'), (2, 'Ate Most'), (3, 'Ate All')], null=True, verbose_name='Breakfast Completeness'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='comments',
            field=models.TextField(max_length=255, null=True, verbose_name='Additional Comments'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, null=True, verbose_name='Report Date'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='first_milk_oz',
            field=models.IntegerField(null=True, verbose_name='First Milk (oz)'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='first_milk_time',
            field=models.TimeField(null=True, verbose_name='First Milk Time'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='fourth_milk_oz',
            field=models.IntegerField(null=True, verbose_name='Fourth Milk (oz)'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='fourth_milk_time',
            field=models.TimeField(null=True, verbose_name='Fourth Milk Time'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='had_am_nap',
            field=models.BooleanField(null=True, verbose_name='Had Morning Nap'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='had_pm_nap',
            field=models.BooleanField(null=True, verbose_name='Had Afternoon Nap'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='lunch',
            field=models.IntegerField(choices=[(0, 'Did Not Eat'), (1, 'Ate A Little'), (2, 'Ate Most'), (3, 'Ate All')], null=True, verbose_name='Lunch Completeness'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='second_milk_oz',
            field=models.IntegerField(null=True, verbose_name='Second Milk (oz)'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='second_milk_time',
            field=models.TimeField(null=True, verbose_name='Second Milk Time'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='third_milk_oz',
            field=models.IntegerField(null=True, verbose_name='Third Milk (oz)'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='third_milk_time',
            field=models.TimeField(null=True, verbose_name='Third Milk Time'),
        ),
    ]
